package com.linuxdroid.linux.bootstrap

import com.linuxdroid.core.logging.LinuxDroidLogger
import com.linuxdroid.core.logging.LogSubsystem
import com.linuxdroid.core.model.Architecture
import com.linuxdroid.core.model.Distribution
import com.linuxdroid.core.runtime.ElfValidator
import java.io.File
import java.nio.file.Files
import java.nio.file.Path

/**
 * Result of individual validation check.
 */
data class ValidationCheckResult(
    val name: String,
    val passed: Boolean,
    val detail: String,
)

/**
 * Comprehensive report generated by [RootfsValidator].
 */
data class RootfsValidationReport(
    val isValid: Boolean,
    val distribution: Distribution,
    val architecture: Architecture,
    val checks: List<ValidationCheckResult>,
    val errors: List<String>,
) {
    fun formatSummary(): String = buildString {
        appendLine("=== ROOTFS VALIDATION REPORT (${distribution.displayName} / ${architecture.abiName}) ===")
        appendLine("Status: ${if (isValid) "PASS" else "FAIL"}")
        checks.forEach { check ->
            appendLine(" [${if (check.passed) "✓" else "✗"}] ${check.name}: ${check.detail}")
        }
        if (errors.isNotEmpty()) {
            appendLine("Errors:")
            errors.forEach { appendLine("  - $it") }
        }
    }.trimEnd()
}

/**
 * Validates structural integrity, mandatory binaries, guest symlink chains,
 * ELF architectures, and PT_INTERP dynamic linkers for Linux root filesystems.
 */
class RootfsValidator(
    private val log: LinuxDroidLogger = LinuxDroidLogger(LogSubsystem.BOOTSTRAP),
) {

    /**
     * Resolves a guest path (e.g. `/lib/ld-linux-aarch64.so.1` or `/bin/sh`) strictly
     * within [rootfsDir], following all symlinks up to [maxHops].
     *
     * Guest absolute symlinks (e.g. `-> /usr/bin/bash`) are resolved relative to [rootfsDir],
     * NOT the Android host root `/`.
     *
     * Returns the host [File] pointing to the final target, or null if broken/escaping/circular.
     */
    fun resolveGuestSymlink(rootfsDir: File, guestPath: String, maxHops: Int = 16): File? {
        val rootfsCanonical = rootfsDir.canonicalFile
        var current = File(rootfsCanonical, guestPath.removePrefix("/"))
        var hops = 0

        while (hops < maxHops) {
            val currentPath: Path = current.toPath()
            if (!Files.isSymbolicLink(currentPath)) {
                // Not a symlink: verify existence and boundary
                if (!current.exists()) return null
                val targetCanonical = current.canonicalFile
                if (!targetCanonical.path.startsWith(rootfsCanonical.path)) {
                    log.warn("[BOOTSTRAP_SYMLINK_VALIDATE] Path traversal out of rootfs detected: ${current.path}")
                    return null
                }
                return current
            }

            // It is a symlink: read link target
            val rawTarget = try {
                Files.readSymbolicLink(currentPath).toString()
            } catch (e: Exception) {
                log.warn("[BOOTSTRAP_SYMLINK_VALIDATE] Failed to read symlink ${current.path}: ${e.message}")
                return null
            }

            hops++
            current = if (rawTarget.startsWith("/")) {
                // Absolute guest link: interpret relative to rootfsDir!
                File(rootfsCanonical, rawTarget.removePrefix("/"))
            } else {
                // Relative link: resolve relative to symlink's parent directory
                File(current.parentFile ?: rootfsCanonical, rawTarget)
            }
        }

        log.warn("[BOOTSTRAP_SYMLINK_VALIDATE] Symlink loop detected for $guestPath (exceeded $maxHops hops)")
        return null
    }

    /**
     * Executes comprehensive validation on [rootfsDir] for [distribution] and [architecture].
     */
    fun validate(
        rootfsDir: File,
        distribution: Distribution,
        architecture: Architecture = Architecture.ARM64,
    ): RootfsValidationReport {
        val checks = mutableListOf<ValidationCheckResult>()
        val errors = mutableListOf<String>()

        log.info("[BOOTSTRAP_VALIDATE] Validating rootfs at ${rootfsDir.path} for ${distribution.displayName} (${architecture.abiName})")

        // 1. Rootfs Directory Existence
        if (!rootfsDir.exists() || !rootfsDir.isDirectory) {
            val msg = "Rootfs directory does not exist or is not a directory: ${rootfsDir.path}"
            errors.add(msg)
            checks.add(ValidationCheckResult("rootfs_directory", false, msg))
            return RootfsValidationReport(false, distribution, architecture, checks, errors)
        }
        checks.add(ValidationCheckResult("rootfs_directory", true, "Directory exists at ${rootfsDir.path}"))

        // 2. Structural Linux Directories
        val requiredDirs = listOf("etc", "usr", "tmp", "dev", "proc", "sys")
        val missingDirs = requiredDirs.filter { !File(rootfsDir, it).exists() }
        if (missingDirs.isNotEmpty()) {
            val msg = "Missing essential rootfs directories: $missingDirs"
            errors.add(msg)
            checks.add(ValidationCheckResult("structural_directories", false, msg))
        } else {
            checks.add(ValidationCheckResult("structural_directories", true, "Essential directories present ($requiredDirs)"))
        }

        // 3. Mandatory Binary Checks: /bin/sh, /bin/bash, /usr/bin/bash, /usr/bin/env, /bin/true
        val requiredBinaries = listOf(
            "/bin/sh",
            "/usr/bin/env",
        )
        for (bin in requiredBinaries) {
            val resolved = resolveGuestSymlink(rootfsDir, bin)
            if (resolved == null || !resolved.exists()) {
                val msg = "Mandatory guest binary missing or broken symlink: $bin"
                errors.add(msg)
                checks.add(ValidationCheckResult("binary_$bin", false, msg))
            } else if (!resolved.canRead()) {
                val msg = "Guest binary not readable: $bin (${resolved.path})"
                errors.add(msg)
                checks.add(ValidationCheckResult("binary_$bin", false, msg))
            } else {
                checks.add(ValidationCheckResult("binary_$bin", true, "Found at ${resolved.path}"))
            }
        }

        // Check for shell (bash or sh)
        val bashResolved = resolveGuestSymlink(rootfsDir, "/bin/bash") ?: resolveGuestSymlink(rootfsDir, "/usr/bin/bash")
        val shResolved = resolveGuestSymlink(rootfsDir, "/bin/sh") ?: resolveGuestSymlink(rootfsDir, "/usr/bin/sh")
        if (bashResolved == null && shResolved == null) {
            val msg = "Neither /bin/bash nor /bin/sh resolved to a usable shell executable"
            errors.add(msg)
            checks.add(ValidationCheckResult("shell_executable", false, msg))
        } else {
            val activeShell = bashResolved ?: shResolved
            checks.add(ValidationCheckResult("shell_executable", true, "Resolved shell at ${activeShell?.path}"))
        }

        // 4. ELF & PT_INTERP Validation
        val elfBinariesToCheck = listOfNotNull(
            bashResolved ?: shResolved,
            resolveGuestSymlink(rootfsDir, "/usr/bin/env"),
            resolveGuestSymlink(rootfsDir, "/bin/true") ?: resolveGuestSymlink(rootfsDir, "/usr/bin/true"),
        ).distinctBy { it.canonicalPath }

        for (elfFile in elfBinariesToCheck) {
            val elfInfo = ElfValidator.readElfInfo(elfFile, architecture.abiName)
            if (!elfInfo.isValid) {
                val msg = "ELF validation failed for ${elfFile.name}: ${elfInfo.detail}"
                errors.add(msg)
                checks.add(ValidationCheckResult("elf_${elfFile.name}", false, msg))
            } else {
                checks.add(ValidationCheckResult("elf_${elfFile.name}", true, elfInfo.detail))

                // If executable is dynamically linked, validate its PT_INTERP dynamic linker
                elfInfo.interpreter?.let { interpGuestPath ->
                    val interpResolved = resolveGuestSymlink(rootfsDir, interpGuestPath)
                    if (interpResolved == null || !interpResolved.exists()) {
                        val msg = "Dynamic interpreter '$interpGuestPath' for ${elfFile.name} missing in rootfs"
                        errors.add(msg)
                        checks.add(ValidationCheckResult("interp_${elfFile.name}", false, msg))
                    } else {
                        val interpElf = ElfValidator.readElfInfo(interpResolved, architecture.abiName)
                        if (!interpElf.isValid) {
                            val msg = "Dynamic interpreter '$interpGuestPath' invalid: ${interpElf.detail}"
                            errors.add(msg)
                            checks.add(ValidationCheckResult("interp_${elfFile.name}", false, msg))
                        } else {
                            checks.add(ValidationCheckResult("interp_${elfFile.name}", true, "Valid dynamic linker at ${interpResolved.path}"))
                        }
                    }
                }
            }
        }

        // 5. Package Manager Configuration
        when (distribution) {
            Distribution.DEBIAN, Distribution.UBUNTU, Distribution.KALI -> {
                val aptSourcesFile = File(rootfsDir, "etc/apt/sources.list")
                val aptSourcesDir = File(rootfsDir, "etc/apt/sources.list.d")
                val hasAptSources = (aptSourcesFile.exists() && aptSourcesFile.length() > 0) ||
                        (aptSourcesDir.isDirectory && (aptSourcesDir.listFiles()?.isNotEmpty() == true))
                if (!hasAptSources) {
                    val msg = "APT package manager configuration (etc/apt/sources.list) missing for ${distribution.displayName}"
                    errors.add(msg)
                    checks.add(ValidationCheckResult("apt_sources", false, msg))
                } else {
                    checks.add(ValidationCheckResult("apt_sources", true, "APT sources configured"))
                }
            }
            else -> {
                checks.add(ValidationCheckResult("package_manager_config", true, "Distribution $distribution checked"))
            }
        }

        val isValid = errors.isEmpty()
        if (isValid) {
            log.info("[BOOTSTRAP_VALIDATE] Rootfs validation PASSED for ${distribution.displayName}")
        } else {
            log.warn("[BOOTSTRAP_VALIDATE] Rootfs validation FAILED for ${distribution.displayName}: $errors")
        }

        return RootfsValidationReport(
            isValid = isValid,
            distribution = distribution,
            architecture = architecture,
            checks = checks,
            errors = errors,
        )
    }
}

