package com.linuxdroid.core.gui

import com.linuxdroid.core.model.GuiError
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.asStateFlow
import java.io.File

/**
 * Builds a `weston.ini` for a LinuxDroid graphical session.
 *
 * Weston is used strictly as the initial Wayland compositor — no shell,
 * desktop environment, or panel is configured. Kept separate from the process
 * management so the generated configuration can be asserted in unit tests.
 */
object WestonConfig {

    /** Maps a selected backend to the Weston backend module name. */
    fun backendModule(backend: CompositorBackend): String = when (backend) {
        // Both present through the LinuxDroid display transport into the Android
        // surface; the difference is whether a GL renderer is used.
        CompositorBackend.ANDROID_SURFACE,
        CompositorBackend.SOFTWARE,
        -> "headless-backend.so"
        CompositorBackend.HEADLESS -> "headless-backend.so"
        CompositorBackend.NESTED_WAYLAND -> "wayland-backend.so"
    }

    fun renderer(backend: CompositorBackend): String = when (backend) {
        CompositorBackend.ANDROID_SURFACE -> "gl"
        else -> "pixman"
    }

    /**
     * Renders the ini contents.
     *
     * `shell=` is left at Weston's default desktop shell only insofar as it is
     * required for surfaces to map; no panel or background is configured,
     * because the LinuxDroid desktop shell is a separate, later roadmap item.
     */
    fun render(
        backend: CompositorBackend,
        geometry: DisplayGeometry,
    ): String = buildString {
        appendLine("# Generated by LinuxDroid. Do not edit; regenerated per session.")
        appendLine("[core]")
        appendLine("backend=${backendModule(backend)}")
        appendLine("renderer=${renderer(backend)}")
        appendLine("idle-time=0")
        appendLine("require-input=false")
        appendLine()
        appendLine("[shell]")
        appendLine("panel-position=none")
        appendLine("locking=false")
        appendLine()
        appendLine("[output]")
        appendLine("name=linuxdroid-0")
        appendLine("mode=${geometry.widthPx}x${geometry.heightPx}")
        appendLine("scale=1")
    }
}

/**
 * Weston-backed [Compositor].
 *
 * Everything Weston-specific is confined to this file plus [WestonConfig]:
 * the GUI runtime only ever talks to the [Compositor] interface, so Weston
 * remains replaceable.
 *
 * The process itself is started through [CompositorProcessLauncher], which is
 * implemented on top of the existing LinuxDroid runtime — no second process
 * execution system is introduced here.
 */
class WestonCompositor(
    private val launcher: CompositorProcessLauncher,
    private val readinessProbe: WaylandReadinessProbe,
    private val log: GuiLog,
    private val geometryProvider: () -> DisplayGeometry?,
    private val executable: String = "weston",
) : Compositor {

    override val id: CompositorId = CompositorId.WESTON

    private val _status = MutableStateFlow(CompositorStatus(id = id, state = GuiState.STOPPED))
    override val statusUpdates: Flow<CompositorStatus> = _status.asStateFlow()
    override val status: CompositorStatus get() = _status.value

    @Volatile
    private var process: CompositorProcess? = null

    override suspend fun isSupported(backend: CompositorBackend): Boolean =
        backend != CompositorBackend.NESTED_WAYLAND && launcher.hasExecutable(executable)

    override suspend fun start(request: CompositorLaunchRequest): CompositorStatus {
        val session = request.session
        // STOPPED/ERROR re-enter the lifecycle through INITIALIZING.
        if (_status.value.state != GuiState.INITIALIZING) {
            transition(GuiState.INITIALIZING, backend = request.backend.backend)
        }
        transition(GuiState.STARTING, backend = request.backend.backend)

        val geometry = geometryProvider() ?: return fail(
            GuiFailureKind.DISPLAY_TRANSPORT_FAILED,
            "no display output available for the compositor",
            "backend=${request.backend.backend}",
        )

        if (!launcher.hasExecutable(executable)) {
            return fail(
                GuiFailureKind.COMPOSITOR_LAUNCH_FAILED,
                "compositor executable missing",
                "executable=$executable rootfs=${launcher.rootfsPath()} reason=ENOENT",
            )
        }

        val configPath = try {
            writeConfig(session, request.backend.backend, geometry)
        } catch (e: Exception) {
            return fail(
                GuiFailureKind.SESSION_SETUP_FAILED,
                "cannot write compositor configuration",
                "reason=${e.message}",
                e,
            )
        }

        val command = buildCommand(session, configPath.guestPath)
        log.info(
            GuiLogCategory.COMPOSITOR,
            "compositor starting: executable=$executable backend=${request.backend.backend} " +
                "socket=${session.socketName} rationale=${request.backend.rationale}",
        )

        val started = try {
            launcher.launch(
                command = command,
                env = session.environment + request.extraEnv,
                workingDirectory = session.runtimeDir,
                bindings = listOf(
                    GuestBinding(session.hostRuntimeDir, session.runtimeDir),
                ),
                logFilePath = compositorLogPath(session),
            )
        } catch (e: Exception) {
            return fail(
                GuiFailureKind.COMPOSITOR_LAUNCH_FAILED,
                "compositor process failed to start",
                "executable=$executable reason=${e.message}",
                e,
            )
        }
        process = started
        log.info(
            GuiLogCategory.COMPOSITOR,
            "compositor process started: pid=${started.pid} handle=${started.handleId}",
        )
        _status.value = _status.value.copy(pid = started.pid, startedAt = System.currentTimeMillis())

        val readiness = readinessProbe.awaitReadyFor(session, started, request.readinessTimeoutMs)
        if (!readiness.ready) {
            val kind = when (readiness.failedStep) {
                ReadinessStep.PROCESS_ALIVE, ReadinessStep.PROCESS_STILL_ALIVE ->
                    GuiFailureKind.COMPOSITOR_CRASHED
                else -> GuiFailureKind.COMPOSITOR_READINESS_TIMEOUT
            }
            // Never leave an unusable compositor process behind.
            runCatching { started.terminate() }
            process = null
            return fail(
                kind,
                "compositor did not become ready",
                "step=${readiness.failedStep} socket=${session.hostSocketPath} ${readiness.detail}",
            )
        }

        log.info(GuiLogCategory.WAYLAND, "wayland socket detected: ${session.socketPath}")
        log.info(
            GuiLogCategory.WAYLAND,
            "wayland readiness verified: socket=${session.socketName} pid=${started.pid}",
        )
        transition(GuiState.READY, backend = request.backend.backend, socket = session.socketName)
        return _status.value
    }

    override suspend fun stop() {
        val current = process
        if (current == null) {
            if (_status.value.state != GuiState.STOPPED) {
                transition(GuiState.STOPPED)
            }
            return
        }
        transition(GuiState.STOPPING)
        log.info(GuiLogCategory.COMPOSITOR, "compositor stopping: pid=${current.pid}")
        val terminated = try {
            current.terminate()
        } catch (e: Exception) {
            log.error(GuiLogCategory.COMPOSITOR, "compositor termination raised an error", e)
            false
        }
        process = null
        if (!terminated) {
            val failure = GuiFailure(
                kind = GuiFailureKind.SHUTDOWN_FAILED,
                message = "compositor did not terminate within the grace period",
                detail = "pid=${current.pid}",
            )
            log.failure(GuiLogCategory.COMPOSITOR, failure)
            _status.value = _status.value.copy(
                state = GuiState.ERROR,
                failure = failure,
                stoppedAt = System.currentTimeMillis(),
            )
            return
        }
        log.info(GuiLogCategory.COMPOSITOR, "compositor terminated: pid=${current.pid}")
        _status.value = _status.value.copy(
            state = GuiState.STOPPED,
            pid = -1,
            waylandSocket = null,
            stoppedAt = System.currentTimeMillis(),
        )
    }

    /** Marks the session RUNNING once clients may connect. Only legal from READY. */
    override fun markRunning() {
        if (_status.value.state == GuiState.READY) {
            transition(GuiState.RUNNING, socket = _status.value.waylandSocket)
        }
    }

    internal fun buildCommand(session: WaylandSessionInfo, configGuestPath: String): List<String> =
        listOf(
            executable,
            "--socket=${session.socketName}",
            "--config=$configGuestPath",
            "--log=${compositorGuestLogPath(session)}",
        )

    private data class ConfigPaths(val hostPath: String, val guestPath: String)

    private fun writeConfig(
        session: WaylandSessionInfo,
        backend: CompositorBackend,
        geometry: DisplayGeometry,
    ): ConfigPaths {
        val hostFile = File(session.hostRuntimeDir, CONFIG_FILE_NAME)
        hostFile.writeText(WestonConfig.render(backend, geometry))
        log.info(
            GuiLogCategory.COMPOSITOR,
            "compositor configuration generated: ${hostFile.path} " +
                "backend=${WestonConfig.backendModule(backend)} " +
                "renderer=${WestonConfig.renderer(backend)} " +
                "mode=${geometry.widthPx}x${geometry.heightPx}",
        )
        return ConfigPaths(hostFile.absolutePath, "${session.runtimeDir}/$CONFIG_FILE_NAME")
    }

    private fun compositorLogPath(session: WaylandSessionInfo): String =
        File(session.hostRuntimeDir, COMPOSITOR_LOG_NAME).absolutePath

    private fun compositorGuestLogPath(session: WaylandSessionInfo): String =
        "${session.runtimeDir}/$COMPOSITOR_LOG_NAME"

    private fun transition(
        next: GuiState,
        backend: CompositorBackend? = _status.value.backend,
        socket: String? = _status.value.waylandSocket,
    ) {
        val current = _status.value.state
        if (current != next && !current.canTransitionTo(next)) {
            throw GuiError("Illegal compositor state transition: $current -> $next")
        }
        _status.value = _status.value.copy(
            state = next,
            backend = backend,
            waylandSocket = socket,
            failure = if (next == GuiState.ERROR) _status.value.failure else null,
        )
    }

    private fun fail(
        kind: GuiFailureKind,
        message: String,
        detail: String,
        cause: Throwable? = null,
    ): Nothing {
        val failure = GuiFailure(kind = kind, message = message, detail = detail, cause = cause)
        log.failure(GuiLogCategory.COMPOSITOR, failure)
        _status.value = _status.value.copy(
            state = GuiState.ERROR,
            failure = failure,
            pid = -1,
            waylandSocket = null,
        )
        throw GuiError(failure.describe(), cause)
    }

    companion object {
        const val CONFIG_FILE_NAME = "weston.ini"
        const val COMPOSITOR_LOG_NAME = "compositor.log"
    }
}

/** Factory so the compositor stays resolvable through [CompositorRegistry]. */
class WestonCompositorFactory(
    private val provider: () -> Compositor,
) : CompositorFactory {
    override val id: CompositorId = CompositorId.WESTON
    override fun create(): Compositor = provider()
}
